# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Azure Pipelines
steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: 'VM-IIS'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'Pay-As-You-Go(945cfaa1-11b8-4f18-8bb1-0763430b4565)'
    subscriptionName: '945cfaa1-11b8-4f18-8bb1-0763430b4565'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DevProject'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'VM-IIS'
    deploymentMode: 'Incremental'




