# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pay-As-You-Go(1)(945cfaa1-11b8-4f18-8bb1-0763430b4565)'
    subscriptionId: '945cfaa1-11b8-4f18-8bb1-0763430b4565'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DevProject'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'VM-IIS/deploy.json'
    deploymentMode: 'Incremental'